# Generated by Django 4.2.11 on 2024-03-19 13:41

from django.db import migrations

def create_default_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('users', 'Profile')

    user = User.objects.create_user(
        username='Pierre',
        email='Pierre.Dupont@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Toulouse',
        age=25,
        gender='Male'
    )

    user = User.objects.create_user(
    username='Marie',
    email='Marie.Lefevre@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Nantes',
        age=47,
        gender='Female'
    )

    user = User.objects.create_user(
    username='Antoine',
    email='Antoine.Leroy@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Paris',
        age=20,
        gender='Male'
    )

    user = User.objects.create_user(
    username='Sylvie',
    email='Sylvie.Morel@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Reims',
        age=35,
        gender='Female'
    )

    user = User.objects.create_user(
    username='Paul',
    email='Paul.Simon@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Montpellier',
        age=54,
        gender='Male'
    )

    user = User.objects.create_user(
    username='Claire',
    email='Claire.Laurent@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Montpellier',
        age=38,
        gender='Other'
    )

    user = User.objects.create_user(
    username='Nicolas',
    email='Nicolas.Girard@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Toulouse',
        age=59,
        gender='Other'
    )

    user = User.objects.create_user(
    username='Sophie',
    email='Sophie.Rousseau@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Nantes',
        age=19,
        gender='Female'
    )

    user = User.objects.create_user(
    username='Julien',
    email='Julien.Fontaine@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Reims',
        age=26,
        gender='Male'
    )

    user = User.objects.create_user(
    username='Emilie',
    email='Emilie.Dubois@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Toulouse',
        age=25,
        gender='Female'
    )

    user = User.objects.create_user(
    username='Vincent',
    email='Vincent.Martin@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Paris',
        age=50,
        gender='Other'
    )

    user = User.objects.create_user(
    username='Elodie',
    email='Elodie.Lucas@example.com',
    )
    Profile.objects.create(
        user=user,
        hometown='Nantes',
        age=19,
        gender='Female'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_users),
    ]
